import { LegalLayout } from "@/components/LegalLayout";

const S = {
  h2: { fontSize: "18px", fontWeight: "bold", marginTop: "40px", marginBottom: "12px", color: "var(--foreground)" } as React.CSSProperties,
  p: { marginBottom: "16px", color: "#475569" } as React.CSSProperties,
  ul: { marginBottom: "16px", paddingLeft: "20px", color: "#475569" } as React.CSSProperties,
};

export default function LegalPage() {
  return (
    <LegalLayout title="Legal Notice" lastUpdated="May 2026">

      <h2 style={S.h2}>1. Identity of the owner</h2>
      <p style={S.p}>
        In compliance with Law 34/2002 of 11 July on Information Society Services and Electronic Commerce (LSSI-CE), the following identifying information is provided:
      </p>
      <ul style={S.ul}>
        <li><strong>Owner:</strong> Raúl Cotrina</li>
        <li><strong>NIF:</strong> 09012736W</li>
        <li><strong>Address:</strong> Avenida de la Coruña 37 1A, San Sebastián de los Reyes, Madrid, Spain</li>
        <li><strong>Email:</strong> raulcotrina@gmail.com</li>
        <li><strong>Website:</strong> https://klipwise.app</li>
      </ul>

      <h2 style={S.h2}>2. Purpose and scope</h2>
      <p style={S.p}>
        This Legal Notice governs access to and use of the website klipwise.app (hereinafter &quot;the Site&quot;) and the services offered through it. Accessing or using the Site implies full and unconditional acceptance of the conditions set out in this Legal Notice.
      </p>

      <h2 style={S.h2}>3. Terms of use</h2>
      <p style={S.p}>The user agrees to:</p>
      <ul style={S.ul}>
        <li>Use the Site and its services lawfully, in compliance with applicable legislation.</li>
        <li>Not use the Site for fraudulent, illegal, or harmful activities.</li>
        <li>Not attempt to access restricted areas of the Site without authorisation.</li>
        <li>Provide accurate and up-to-date information in registration forms.</li>
      </ul>

      <h2 style={S.h2}>4. Intellectual and industrial property</h2>
      <p style={S.p}>
        All content on the Site (text, images, source code, logos and other elements) is the property of the owner or used under licence. Reproduction, distribution, public communication or transformation without the express authorisation of the owner is prohibited.
      </p>
      <p style={S.p}>
        The trade name &quot;Klipwise&quot; and the domain klipwise.app are used exclusively by the owner for the provision of this service.
      </p>

      <h2 style={S.h2}>5. Limitation of liability</h2>
      <p style={S.p}>
        The owner does not guarantee the continuous availability of the Site and accepts no liability for damages arising from interruptions, technical errors or unauthorised access beyond their control. Content generated by artificial intelligence is for guidance only and does not constitute professional advice of any kind.
      </p>

      <h2 style={S.h2}>6. Applicable law and jurisdiction</h2>
      <p style={S.p}>
        This Legal Notice is governed by Spanish law. For the resolution of any dispute arising from access to or use of the Site, the parties submit to the jurisdiction of the Courts and Tribunals of Madrid, expressly waiving any other jurisdiction that may apply to them.
      </p>

    </LegalLayout>
  );
}
